FROM golang:1.20-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./
COPY ./request-generator ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping

CMD [ "/docker-gs-ping" ]