// Code generated by MockGen. DO NOT EDIT.
// Source: calculation-service/service/ohlc/repository/ohlc.go

// Package ohlcRepository is a generated GoMock package.
package ohlcRepository

import (
	reflect "reflect"

	ohlcEntity "github.com/fadellh/stock-ohlc/calculation-service/service/ohlc/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockOhlcRepository is a mock of OhlcRepository interface.
type MockOhlcRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOhlcRepositoryMockRecorder
}

// MockOhlcRepositoryMockRecorder is the mock recorder for MockOhlcRepository.
type MockOhlcRepositoryMockRecorder struct {
	mock *MockOhlcRepository
}

// NewMockOhlcRepository creates a new mock instance.
func NewMockOhlcRepository(ctrl *gomock.Controller) *MockOhlcRepository {
	mock := &MockOhlcRepository{ctrl: ctrl}
	mock.recorder = &MockOhlcRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOhlcRepository) EXPECT() *MockOhlcRepositoryMockRecorder {
	return m.recorder
}

// GetRedis mocks base method.
func (m *MockOhlcRepository) GetRedis(req ohlcEntity.OhlcStock) (*ohlcEntity.OhlcStock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedis", req)
	ret0, _ := ret[0].(*ohlcEntity.OhlcStock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRedis indicates an expected call of GetRedis.
func (mr *MockOhlcRepositoryMockRecorder) GetRedis(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedis", reflect.TypeOf((*MockOhlcRepository)(nil).GetRedis), req)
}

// StoreRedis mocks base method.
func (m *MockOhlcRepository) StoreRedis(req ohlcEntity.OhlcStock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRedis", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRedis indicates an expected call of StoreRedis.
func (mr *MockOhlcRepositoryMockRecorder) StoreRedis(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRedis", reflect.TypeOf((*MockOhlcRepository)(nil).StoreRedis), req)
}
