// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: summary-service/proto/ohlc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OhlcClient is the client API for Ohlc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OhlcClient interface {
	GetOhlcSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error)
}

type ohlcClient struct {
	cc grpc.ClientConnInterface
}

func NewOhlcClient(cc grpc.ClientConnInterface) OhlcClient {
	return &ohlcClient{cc}
}

func (c *ohlcClient) GetOhlcSummary(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (*SummaryResponse, error) {
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, "/proto.Ohlc/GetOhlcSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OhlcServer is the server API for Ohlc service.
// All implementations must embed UnimplementedOhlcServer
// for forward compatibility
type OhlcServer interface {
	GetOhlcSummary(context.Context, *SummaryRequest) (*SummaryResponse, error)
	mustEmbedUnimplementedOhlcServer()
}

// UnimplementedOhlcServer must be embedded to have forward compatible implementations.
type UnimplementedOhlcServer struct {
}

func (UnimplementedOhlcServer) GetOhlcSummary(context.Context, *SummaryRequest) (*SummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOhlcSummary not implemented")
}
func (UnimplementedOhlcServer) mustEmbedUnimplementedOhlcServer() {}

// UnsafeOhlcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OhlcServer will
// result in compilation errors.
type UnsafeOhlcServer interface {
	mustEmbedUnimplementedOhlcServer()
}

func RegisterOhlcServer(s grpc.ServiceRegistrar, srv OhlcServer) {
	s.RegisterService(&Ohlc_ServiceDesc, srv)
}

func _Ohlc_GetOhlcSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OhlcServer).GetOhlcSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Ohlc/GetOhlcSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OhlcServer).GetOhlcSummary(ctx, req.(*SummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ohlc_ServiceDesc is the grpc.ServiceDesc for Ohlc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ohlc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Ohlc",
	HandlerType: (*OhlcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOhlcSummary",
			Handler:    _Ohlc_GetOhlcSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "summary-service/proto/ohlc.proto",
}
